DEFAULT_GRYPE_EXECUTABLE = "grype"
DEFAULT_SCAN_TIMEOUT = 600
DEFAULT_VERSION_TIMEOUT = 30

VULNERABILITY_DIRECTORY = "vulnerabilities"
VULNERABILITY_RUN_PREFIX = "vulnerability-"
VULNERABILITY_REPORT_FILENAME = "vulnerability-results.json"
