DEFAULT_GRYPE_EXECUTABLE = "grype"
DEFAULT_SCAN_TIMEOUT = 600
DEFAULT_VERSION_TIMEOUT = 30

GRYPE_VERSION_COMMAND = "version"
GRYPE_SCAN_OUTPUT = "json"
GRYPE_SBOM_PREFIX = "sbom:"
GRYPE_OUTPUT_OPTION = "--output"
GRYPE_FILE_OPTION = "--file"

VULNERABILITY_DIRECTORY = "vulnerabilities"
VULNERABILITY_RUN_PREFIX = "vulnerability-"
VULNERABILITY_REPORT_FILENAME = "vulnerability-results.json"
