DEFAULT_SYFT_EXECUTABLE = "syft"
DEFAULT_SCAN_TIMEOUT = 600
DEFAULT_VERSION_TIMEOUT = 30
DEFAULT_GIT_TIMEOUT = 30

SYFT_SBOM_OUTPUT = "cyclonedx-json"

SBOM_DIRECTORY = "sboms"
SBOM_RUN_PREFIX = "sbom-"
SBOM_REPORT_FILENAME = "sbom-results.json"
