import re

DEFAULT_SYFT_EXECUTABLE = "syft"
DEFAULT_SCAN_TIMEOUT = 600
DEFAULT_VERSION_TIMEOUT = 30
DEFAULT_GIT_TIMEOUT = 30

SYFT_VERSION_COMMAND = "version"
SYFT_SCAN_COMMAND = "scan"
SYFT_VERSION_OUTPUT = "json"
SYFT_SBOM_OUTPUT = "cyclonedx-json"

GIT_EXECUTABLE = "git"
GIT_COMMIT_COMMAND = "rev-parse"
GIT_HEAD_REFERENCE = "HEAD"

SBOM_DIRECTORY = "sboms"
SBOM_RUN_PREFIX = "sbom-"
SBOM_REPORT_FILENAME = "sbom-results.json"
